### YamlMime:TSType
name: ConfigurePhoneNumberOptions
uid: '@azure/communication-administration.ConfigurePhoneNumberOptions|preview'
package: '@azure/communication-administration'
summary: Options for configuring a phone number.
fullName: ConfigurePhoneNumberOptions
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: abortSignal
    uid: >-
      @azure/communication-administration.ConfigurePhoneNumberOptions.abortSignal|preview
    package: '@azure/communication-administration'
    summary: The signal which can be used to abort requests.
    fullName: abortSignal
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'abortSignal?: AbortSignalLike'
      return:
        type: AbortSignalLike
        description: ''
  - name: applicationId
    uid: >-
      @azure/communication-administration.ConfigurePhoneNumberOptions.applicationId|preview
    package: '@azure/communication-administration'
    summary: Associates the phone number with a given applicationId.
    fullName: applicationId
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'applicationId?: string'
      return:
        type: string
        description: ''
  - name: azurePstnTargetId
    uid: >-
      @azure/communication-administration.ConfigurePhoneNumberOptions.azurePstnTargetId|preview
    package: '@azure/communication-administration'
    summary: Routable TargetId for the ACS Number
    fullName: azurePstnTargetId
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'azurePstnTargetId?: string'
      return:
        type: string
        description: ''
  - name: requestOptions
    uid: >-
      @azure/communication-administration.ConfigurePhoneNumberOptions.requestOptions|preview
    package: '@azure/communication-administration'
    summary: Options used when creating and sending HTTP requests for this operation.
    fullName: requestOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'requestOptions?: OperationRequestOptions'
      return:
        type: OperationRequestOptions
        description: ''
  - name: tracingOptions
    uid: >-
      @azure/communication-administration.ConfigurePhoneNumberOptions.tracingOptions|preview
    package: '@azure/communication-administration'
    summary: Options used when tracing is enabled.
    fullName: tracingOptions
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tracingOptions?: OperationTracingOptions'
      return:
        type: OperationTracingOptions
        description: ''
extends: OperationOptions
