### YamlMime:TSType
name: NumberConfiguration
uid: '@azure/communication-administration.NumberConfiguration|preview'
package: '@azure/communication-administration'
summary: Definition for number configuration
fullName: NumberConfiguration
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: phoneNumber
    uid: '@azure/communication-administration.NumberConfiguration.phoneNumber|preview'
    package: '@azure/communication-administration'
    summary: The phone number to configure
    fullName: phoneNumber
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'phoneNumber: string'
      return:
        type: string
        description: ''
  - name: pstnConfiguration
    uid: '@azure/communication-administration.NumberConfiguration.pstnConfiguration|preview'
    package: '@azure/communication-administration'
    summary: Definition for pstn number configuration
    fullName: pstnConfiguration
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'pstnConfiguration: PstnConfiguration'
      return:
        type: <xref uid="@azure/communication-administration.PstnConfiguration|preview" />
        description: ''
