### YamlMime:TSType
name: NumberConfigurationResponse
uid: '@azure/communication-administration.NumberConfigurationResponse|preview'
package: '@azure/communication-administration'
summary: Definition for number configuration
fullName: NumberConfigurationResponse
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: pstnConfiguration
    uid: >-
      @azure/communication-administration.NumberConfigurationResponse.pstnConfiguration|preview
    package: '@azure/communication-administration'
    summary: Definition for pstn number configuration
    fullName: pstnConfiguration
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'pstnConfiguration: PstnConfiguration'
      return:
        type: <xref uid="@azure/communication-administration.PstnConfiguration|preview" />
        description: ''
