### YamlMime:TSType
name: ShareSmbSettings
uid: '@azure/storage-file-share.ShareSmbSettings|latest'
package: '@azure/storage-file-share'
summary: Settings for SMB protocol.
fullName: ShareSmbSettings
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: multichannel
    uid: '@azure/storage-file-share.ShareSmbSettings.multichannel|latest'
    package: '@azure/storage-file-share'
    summary: Settings for SMB Multichannel.
    fullName: multichannel
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'multichannel?: SmbMultichannel'
      return:
        type: <xref uid="@azure/storage-file-share.SmbMultichannel|latest" />
        description: ''
