### YamlMime:TSTypeAlias
name: MigrationConfigsListNextResponse
uid: '@azure/arm-servicebus.MigrationConfigsListNextResponse|latest'
package: '@azure/arm-servicebus'
summary: Contains response data for the listNext operation.
fullName: MigrationConfigsListNextResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigsListNextResponse = MigrationConfigListResult & {
  _response: Object }
