### YamlMime:TSTypeAlias
name: MigrationConfigsGetResponse
uid: '@azure/arm-servicebus.MigrationConfigsGetResponse|latest'
package: '@azure/arm-servicebus'
summary: Contains response data for the get operation.
fullName: MigrationConfigsGetResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type MigrationConfigsGetResponse = MigrationConfigProperties & { _response:
  Object }
