### YamlMime:TSType
name: Logging
uid: '@azure/storage-blob.Logging|legacy'
package: '@azure/storage-blob'
summary: Azure Analytics Logging settings.
fullName: Logging
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: deleteProperty
    uid: '@azure/storage-blob.Logging.deleteProperty|legacy'
    package: '@azure/storage-blob'
    summary: Indicates whether all delete requests should be logged.
    fullName: deleteProperty
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'deleteProperty: boolean'
      return:
        type: boolean
        description: ''
  - name: read
    uid: '@azure/storage-blob.Logging.read|legacy'
    package: '@azure/storage-blob'
    summary: Indicates whether all read requests should be logged.
    fullName: read
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'read: boolean'
      return:
        type: boolean
        description: ''
  - name: retentionPolicy
    uid: '@azure/storage-blob.Logging.retentionPolicy|legacy'
    package: '@azure/storage-blob'
    summary: ''
    fullName: retentionPolicy
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'retentionPolicy: RetentionPolicy'
      return:
        type: <xref uid="@azure/storage-blob.RetentionPolicy|legacy" />
        description: ''
  - name: version
    uid: '@azure/storage-blob.Logging.version|legacy'
    package: '@azure/storage-blob'
    summary: The version of Storage Analytics to configure.
    fullName: version
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'version: string'
      return:
        type: string
        description: ''
  - name: write
    uid: '@azure/storage-blob.Logging.write|legacy'
    package: '@azure/storage-blob'
    summary: Indicates whether all write requests should be logged.
    fullName: write
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'write: boolean'
      return:
        type: boolean
        description: ''
