### YamlMime:TSType
name: Service
uid: '@azure/storage-blob.Service|legacy'
package: '@azure/storage-blob'
summary: Class representing a Service.
fullName: Service
remarks: ''
isPreview: false
isDeprecated: false
type: class
constructors:
  - name: Service(StorageClientContext)
    uid: '@azure/storage-blob.Service.constructor|legacy'
    package: '@azure/storage-blob'
    summary: Create a Service.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'new Service(client: StorageClientContext)'
      parameters:
        - id: client
          type: <xref uid="@azure/storage-blob.StorageClientContext|legacy" />
          description: |
            Reference to the service client.
methods:
  - name: getAccountInfo(msRest.RequestOptionsBase)
    uid: '@azure/storage-blob.Service.getAccountInfo|legacy'
    package: '@azure/storage-blob'
    summary: Returns the sku name and account kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function getAccountInfo(options?: msRest.RequestOptionsBase)'
      parameters:
        - id: options
          type: <xref uid="msRest.RequestOptionsBase" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/storage-blob.ServiceGetAccountInfoResponse|legacy" />&gt;
        description: Promise<Models.ServiceGetAccountInfoResponse>
  - name: 'getAccountInfo(RequestOptionsBase, ServiceCallback<void>)'
    uid: '@azure/storage-blob.Service.getAccountInfo_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getAccountInfo(options: RequestOptionsBase, callback:
        ServiceCallback<void>)
      parameters:
        - id: options
          type: RequestOptionsBase
          description: The optional parameters
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
  - name: getAccountInfo(ServiceCallback<void>)
    uid: '@azure/storage-blob.Service.getAccountInfo_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function getAccountInfo(callback: ServiceCallback<void>)'
      parameters:
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
  - name: getProperties(Models.ServiceGetPropertiesOptionalParams)
    uid: '@azure/storage-blob.Service.getProperties|legacy'
    package: '@azure/storage-blob'
    summary: >-
      gets the properties of a storage account's Blob service, including
      properties for Storage

      Analytics and CORS (Cross-Origin Resource Sharing) rules.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getProperties(options?:
        Models.ServiceGetPropertiesOptionalParams)
      parameters:
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceGetPropertiesOptionalParams|legacy" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/storage-blob.ServiceGetPropertiesResponse|legacy" />&gt;
        description: Promise<Models.ServiceGetPropertiesResponse>
  - name: getProperties(ServiceCallback<StorageServiceProperties>)
    uid: '@azure/storage-blob.Service.getProperties_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getProperties(callback:
        ServiceCallback<StorageServiceProperties>)
      parameters:
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.StorageServiceProperties|legacy" />&gt;
          description: |
            The callback
  - name: >-
      getProperties(ServiceGetPropertiesOptionalParams,
      ServiceCallback<StorageServiceProperties>)
    uid: '@azure/storage-blob.Service.getProperties_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getProperties(options: ServiceGetPropertiesOptionalParams,
        callback: ServiceCallback<StorageServiceProperties>)
      parameters:
        - id: options
          type: >-
            <xref uid="@azure/storage-blob.ServiceGetPropertiesOptionalParams|legacy"
            />
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.StorageServiceProperties|legacy" />&gt;
          description: |
            The callback
  - name: getStatistics(Models.ServiceGetStatisticsOptionalParams)
    uid: '@azure/storage-blob.Service.getStatistics|legacy'
    package: '@azure/storage-blob'
    summary: >-
      Retrieves statistics related to replication for the Blob service. It is
      only available on the

      secondary location endpoint when read-access geo-redundant replication is
      enabled for the

      storage account.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getStatistics(options?:
        Models.ServiceGetStatisticsOptionalParams)
      parameters:
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceGetStatisticsOptionalParams|legacy" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/storage-blob.ServiceGetStatisticsResponse|legacy" />&gt;
        description: Promise<Models.ServiceGetStatisticsResponse>
  - name: getStatistics(ServiceCallback<StorageServiceStats>)
    uid: '@azure/storage-blob.Service.getStatistics_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'function getStatistics(callback: ServiceCallback<StorageServiceStats>)'
      parameters:
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.StorageServiceStats|legacy" />&gt;
          description: |
            The callback
  - name: >-
      getStatistics(ServiceGetStatisticsOptionalParams,
      ServiceCallback<StorageServiceStats>)
    uid: '@azure/storage-blob.Service.getStatistics_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getStatistics(options: ServiceGetStatisticsOptionalParams,
        callback: ServiceCallback<StorageServiceStats>)
      parameters:
        - id: options
          type: >-
            <xref uid="@azure/storage-blob.ServiceGetStatisticsOptionalParams|legacy"
            />
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.StorageServiceStats|legacy" />&gt;
          description: |
            The callback
  - name: >-
      getUserDelegationKey(KeyInfo,
      Models.ServiceGetUserDelegationKeyOptionalParams)
    uid: '@azure/storage-blob.Service.getUserDelegationKey|legacy'
    package: '@azure/storage-blob'
    summary: >-
      Retrieves a user delegation key for the Blob service. This is only a valid
      operation when using

      bearer token authentication.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getUserDelegationKey(keyInfo: KeyInfo, options?:
        Models.ServiceGetUserDelegationKeyOptionalParams)
      parameters:
        - id: keyInfo
          type: <xref uid="@azure/storage-blob.KeyInfo|legacy" />
          description: ''
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceGetUserDelegationKeyOptionalParams|legacy" />
          description: ''
      return:
        type: >-
          Promise&lt;<xref uid="Models.ServiceGetUserDelegationKeyResponse"
          />&gt;
        description: Promise<Models.ServiceGetUserDelegationKeyResponse>
  - name: 'getUserDelegationKey(KeyInfo, ServiceCallback<UserDelegationKey>)'
    uid: '@azure/storage-blob.Service.getUserDelegationKey_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getUserDelegationKey(keyInfo: KeyInfo, callback:
        ServiceCallback<UserDelegationKey>)
      parameters:
        - id: keyInfo
          type: <xref uid="@azure/storage-blob.KeyInfo|legacy" />
          description: ''
        - id: callback
          type: >-
            ServiceCallback&lt;<xref uid="@azure/storage-blob.UserDelegationKey|legacy"
            />&gt;
          description: |
            The callback
  - name: >-
      getUserDelegationKey(KeyInfo, ServiceGetUserDelegationKeyOptionalParams,
      ServiceCallback<UserDelegationKey>)
    uid: '@azure/storage-blob.Service.getUserDelegationKey_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function getUserDelegationKey(keyInfo: KeyInfo, options:
        ServiceGetUserDelegationKeyOptionalParams, callback:
        ServiceCallback<UserDelegationKey>)
      parameters:
        - id: keyInfo
          type: <xref uid="@azure/storage-blob.KeyInfo|legacy" />
          description: ''
        - id: options
          type: >-
            <xref
            uid="@azure/storage-blob.ServiceGetUserDelegationKeyOptionalParams|legacy"
            />
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref uid="@azure/storage-blob.UserDelegationKey|legacy"
            />&gt;
          description: |
            The callback
  - name: listContainersSegment(Models.ServiceListContainersSegmentOptionalParams)
    uid: '@azure/storage-blob.Service.listContainersSegment|legacy'
    package: '@azure/storage-blob'
    summary: >-
      The List Containers Segment operation returns a list of the containers
      under the specified

      account
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function listContainersSegment(options?:
        Models.ServiceListContainersSegmentOptionalParams)
      parameters:
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceListContainersSegmentOptionalParams|legacy" />
          description: ''
      return:
        type: >-
          Promise&lt;<xref uid="Models.ServiceListContainersSegmentResponse"
          />&gt;
        description: Promise<Models.ServiceListContainersSegmentResponse>
  - name: listContainersSegment(ServiceCallback<ListContainersSegmentResponse>)
    uid: '@azure/storage-blob.Service.listContainersSegment_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function listContainersSegment(callback:
        ServiceCallback<ListContainersSegmentResponse>)
      parameters:
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.ListContainersSegmentResponse|legacy" />&gt;
          description: |
            The callback
  - name: >-
      listContainersSegment(ServiceListContainersSegmentOptionalParams,
      ServiceCallback<ListContainersSegmentResponse>)
    uid: '@azure/storage-blob.Service.listContainersSegment_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function listContainersSegment(options:
        ServiceListContainersSegmentOptionalParams, callback:
        ServiceCallback<ListContainersSegmentResponse>)
      parameters:
        - id: options
          type: >-
            <xref
            uid="@azure/storage-blob.ServiceListContainersSegmentOptionalParams|legacy"
            />
          description: The optional parameters
        - id: callback
          type: >-
            ServiceCallback&lt;<xref
            uid="@azure/storage-blob.ListContainersSegmentResponse|legacy" />&gt;
          description: |
            The callback
  - name: >-
      setProperties(StorageServiceProperties,
      Models.ServiceSetPropertiesOptionalParams)
    uid: '@azure/storage-blob.Service.setProperties|legacy'
    package: '@azure/storage-blob'
    summary: >-
      Sets properties for a storage account's Blob service endpoint, including
      properties for Storage

      Analytics and CORS (Cross-Origin Resource Sharing) rules
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function setProperties(storageServiceProperties:
        StorageServiceProperties, options?:
        Models.ServiceSetPropertiesOptionalParams)
      parameters:
        - id: storageServiceProperties
          type: <xref uid="@azure/storage-blob.StorageServiceProperties|legacy" />
          description: The StorageService properties.
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceSetPropertiesOptionalParams|legacy" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/storage-blob.ServiceSetPropertiesResponse|legacy" />&gt;
        description: Promise<Models.ServiceSetPropertiesResponse>
  - name: 'setProperties(StorageServiceProperties, ServiceCallback<void>)'
    uid: '@azure/storage-blob.Service.setProperties_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function setProperties(storageServiceProperties:
        StorageServiceProperties, callback: ServiceCallback<void>)
      parameters:
        - id: storageServiceProperties
          type: <xref uid="@azure/storage-blob.StorageServiceProperties|legacy" />
          description: The StorageService properties.
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
  - name: >-
      setProperties(StorageServiceProperties,
      ServiceSetPropertiesOptionalParams, ServiceCallback<void>)
    uid: '@azure/storage-blob.Service.setProperties_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function setProperties(storageServiceProperties:
        StorageServiceProperties, options: ServiceSetPropertiesOptionalParams,
        callback: ServiceCallback<void>)
      parameters:
        - id: storageServiceProperties
          type: <xref uid="@azure/storage-blob.StorageServiceProperties|legacy" />
          description: The StorageService properties.
        - id: options
          type: >-
            <xref uid="@azure/storage-blob.ServiceSetPropertiesOptionalParams|legacy"
            />
          description: The optional parameters
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
  - name: >-
      submitBatch(msRest.HttpRequestBody, number, string,
      Models.ServiceSubmitBatchOptionalParams)
    uid: '@azure/storage-blob.Service.submitBatch|legacy'
    package: '@azure/storage-blob'
    summary: >-
      The Batch operation allows multiple API calls to be embedded into a single
      HTTP request.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function submitBatch(body: msRest.HttpRequestBody, contentLength:
        number, multipartContentType: string, options?:
        Models.ServiceSubmitBatchOptionalParams)
      parameters:
        - id: body
          type: <xref uid="msRest.HttpRequestBody" />
          description: Initial data
        - id: contentLength
          type: number
          description: The length of the request.
        - id: multipartContentType
          type: string
          description: >-
            Required. The value of this header must be multipart/mixed with a

            batch boundary. Example header value: multipart/mixed;
            boundary=batch_<GUID>
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceSubmitBatchOptionalParams|legacy" />
          description: ''
      return:
        type: Promise&lt;<xref uid="@azure/storage-blob.ServiceSubmitBatchResponse|legacy" />&gt;
        description: Promise<Models.ServiceSubmitBatchResponse>
  - name: 'submitBatch(msRest.HttpRequestBody, number, string, ServiceCallback<void>)'
    uid: '@azure/storage-blob.Service.submitBatch_1|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function submitBatch(body: msRest.HttpRequestBody, contentLength:
        number, multipartContentType: string, callback: ServiceCallback<void>)
      parameters:
        - id: body
          type: <xref uid="msRest.HttpRequestBody" />
          description: Initial data
        - id: contentLength
          type: number
          description: The length of the request.
        - id: multipartContentType
          type: string
          description: >-
            Required. The value of this header must be multipart/mixed with a

            batch boundary. Example header value: multipart/mixed;
            boundary=batch_<GUID>
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
  - name: >-
      submitBatch(msRest.HttpRequestBody, number, string,
      ServiceSubmitBatchOptionalParams, ServiceCallback<void>)
    uid: '@azure/storage-blob.Service.submitBatch_2|legacy'
    package: '@azure/storage-blob'
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        function submitBatch(body: msRest.HttpRequestBody, contentLength:
        number, multipartContentType: string, options:
        ServiceSubmitBatchOptionalParams, callback: ServiceCallback<void>)
      parameters:
        - id: body
          type: <xref uid="msRest.HttpRequestBody" />
          description: Initial data
        - id: contentLength
          type: number
          description: The length of the request.
        - id: multipartContentType
          type: string
          description: >-
            Required. The value of this header must be multipart/mixed with a

            batch boundary. Example header value: multipart/mixed;
            boundary=batch_<GUID>
        - id: options
          type: <xref uid="@azure/storage-blob.ServiceSubmitBatchOptionalParams|legacy" />
          description: The optional parameters
        - id: callback
          type: ServiceCallback&lt;void&gt;
          description: |
            The callback
