### YamlMime:TSType
name: GetConfigurationHeaders
uid: '@azure/app-configuration.GetConfigurationHeaders|latest'
package: '@azure/app-configuration'
summary: Headers from getting a ConfigurationSetting.
fullName: GetConfigurationHeaders
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: syncToken
    uid: '@azure/app-configuration.GetConfigurationHeaders.syncToken|latest'
    package: '@azure/app-configuration'
    summary: >-
      Enables real-time consistency between requests by providing the returned
      value in the next

      request made to the server.
    fullName: syncToken
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'syncToken?: string'
      return:
        type: string
        description: ''
extends: <xref uid="@azure/app-configuration.SyncTokenHeaderField|latest" />
