### YamlMime:TSType
name: ListConfigurationSettingPage
uid: '@azure/app-configuration.ListConfigurationSettingPage|latest'
package: '@azure/app-configuration'
summary: A page of configuration settings and the corresponding HTTP response
fullName: ListConfigurationSettingPage
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: items
    uid: '@azure/app-configuration.ListConfigurationSettingPage.items|latest'
    package: '@azure/app-configuration'
    summary: The configuration settings for this page of results.
    fullName: items
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'items: ConfigurationSetting[]'
      return:
        type: '<xref uid="@azure/app-configuration.ConfigurationSetting|latest" />[]'
        description: ''
extends: >-
  <xref uid="@azure/app-configuration.HttpResponseField|latest" />&lt;<xref
  uid="@azure/app-configuration.SyncTokenHeaderField|latest" />&gt;
