### YamlMime:TSType
name: ConfigurationStore
uid: '@azure/arm-appconfiguration.ConfigurationStore|latest'
package: '@azure/arm-appconfiguration'
summary: >-
  The configuration store along with all resource properties. The Configuration
  Store will have

  all information to begin utilizing it.
fullName: ConfigurationStore
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: creationDate
    uid: '@azure/arm-appconfiguration.ConfigurationStore.creationDate|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The creation date of configuration store.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: creationDate
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'creationDate?: Date'
      return:
        type: Date
        description: ''
  - name: encryption
    uid: '@azure/arm-appconfiguration.ConfigurationStore.encryption|latest'
    package: '@azure/arm-appconfiguration'
    summary: The encryption settings of the configuration store.
    fullName: encryption
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'encryption?: EncryptionProperties'
      return:
        type: <xref uid="@azure/arm-appconfiguration.EncryptionProperties|latest" />
        description: ''
  - name: endpoint
    uid: '@azure/arm-appconfiguration.ConfigurationStore.endpoint|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The DNS endpoint where the configuration store API will be available.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: endpoint
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'endpoint?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: id
    uid: '@azure/arm-appconfiguration.ConfigurationStore.id|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The resource ID.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: id
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'id?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: identity
    uid: '@azure/arm-appconfiguration.ConfigurationStore.identity|latest'
    package: '@azure/arm-appconfiguration'
    summary: 'The managed identity information, if configured.'
    fullName: identity
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'identity?: ResourceIdentity'
      return:
        type: <xref uid="@azure/arm-appconfiguration.ResourceIdentity|latest" />
        description: ''
  - name: location
    uid: '@azure/arm-appconfiguration.ConfigurationStore.location|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The location of the resource. This cannot be changed after the resource is
      created.
    fullName: location
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'location: string'
      return:
        type: string
        description: ''
  - name: name
    uid: '@azure/arm-appconfiguration.ConfigurationStore.name|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The name of the resource.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: name
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'name?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: privateEndpointConnections
    uid: '@azure/arm-appconfiguration.ConfigurationStore.privateEndpointConnections|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The list of private endpoint connections that are set up for this
      resource.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: privateEndpointConnections
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'privateEndpointConnections?: PrivateEndpointConnectionReference[]'
      return:
        type: >-
          <xref
          uid="@azure/arm-appconfiguration.PrivateEndpointConnectionReference|latest"
          />[]
        description: ''
  - name: provisioningState
    uid: '@azure/arm-appconfiguration.ConfigurationStore.provisioningState|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The provisioning state of the configuration store. Possible values
      include: 'Creating',

      'Updating', 'Deleting', 'Succeeded', 'Failed', 'Canceled'

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: provisioningState
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'provisioningState?: ProvisioningState'
      return:
        type: <xref uid="@azure/arm-appconfiguration.ProvisioningState|latest" />
        description: ''
  - name: publicNetworkAccess
    uid: '@azure/arm-appconfiguration.ConfigurationStore.publicNetworkAccess|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      Control permission for data plane traffic coming from public networks
      while private endpoint

      is enabled. Possible values include: 'Enabled', 'Disabled'
    fullName: publicNetworkAccess
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'publicNetworkAccess?: PublicNetworkAccess'
      return:
        type: <xref uid="@azure/arm-appconfiguration.PublicNetworkAccess|latest" />
        description: ''
  - name: sku
    uid: '@azure/arm-appconfiguration.ConfigurationStore.sku|latest'
    package: '@azure/arm-appconfiguration'
    summary: The sku of the configuration store.
    fullName: sku
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sku: Sku'
      return:
        type: <xref uid="@azure/arm-appconfiguration.Sku|latest" />
        description: ''
  - name: tags
    uid: '@azure/arm-appconfiguration.ConfigurationStore.tags|latest'
    package: '@azure/arm-appconfiguration'
    summary: The tags of the resource.
    fullName: tags
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tags?: undefined | [key: string]: string'
      return:
        type: 'undefined | [key: string]: string'
        description: ''
  - name: type
    uid: '@azure/arm-appconfiguration.ConfigurationStore.type|latest'
    package: '@azure/arm-appconfiguration'
    summary: >-
      The type of the resource.

      **NOTE: This property will not be serialized. It can only be populated by
      the server.**
    fullName: type
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'type?: undefined | string'
      return:
        type: undefined | string
        description: ''
extends: <xref uid="@azure/arm-appconfiguration.Resource|latest" />
