### YamlMime:TSTypeAlias
name: ConfigurationStoresUpdateResponse
uid: '@azure/arm-appconfiguration.ConfigurationStoresUpdateResponse|latest'
package: '@azure/arm-appconfiguration'
summary: Contains response data for the update operation.
fullName: ConfigurationStoresUpdateResponse
remarks: ''
isPreview: false
isDeprecated: false
syntax: >-
  type ConfigurationStoresUpdateResponse = ConfigurationStore & { _response:
  Object }
