### YamlMime:TSType
name: ConfigurationStoreUpdateParameters
uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters|latest'
package: '@azure/arm-appconfiguration'
summary: The parameters for updating a configuration store.
fullName: ConfigurationStoreUpdateParameters
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: encryption
    uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.encryption|latest'
    package: '@azure/arm-appconfiguration'
    summary: The encryption settings of the configuration store.
    fullName: encryption
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'encryption?: EncryptionProperties'
      return:
        type: <xref uid="@azure/arm-appconfiguration.EncryptionProperties|latest" />
        description: ''
  - name: identity
    uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.identity|latest'
    package: '@azure/arm-appconfiguration'
    summary: The managed identity information for the configuration store.
    fullName: identity
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'identity?: ResourceIdentity'
      return:
        type: <xref uid="@azure/arm-appconfiguration.ResourceIdentity|latest" />
        description: ''
  - name: publicNetworkAccess
    uid: >-
      @azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.publicNetworkAccess|latest
    package: '@azure/arm-appconfiguration'
    summary: >-
      Control permission for data plane traffic coming from public networks
      while private endpoint

      is enabled. Possible values include: 'Enabled', 'Disabled'
    fullName: publicNetworkAccess
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'publicNetworkAccess?: PublicNetworkAccess'
      return:
        type: <xref uid="@azure/arm-appconfiguration.PublicNetworkAccess|latest" />
        description: ''
  - name: sku
    uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.sku|latest'
    package: '@azure/arm-appconfiguration'
    summary: The SKU of the configuration store.
    fullName: sku
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sku?: Sku'
      return:
        type: <xref uid="@azure/arm-appconfiguration.Sku|latest" />
        description: ''
  - name: tags
    uid: '@azure/arm-appconfiguration.ConfigurationStoreUpdateParameters.tags|latest'
    package: '@azure/arm-appconfiguration'
    summary: The ARM resource tags.
    fullName: tags
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'tags?: undefined | [key: string]: string'
      return:
        type: 'undefined | [key: string]: string'
        description: ''
