### YamlMime:TSTypeAlias
name: TrainingStatus
uid: '@azure/ai-form-recognizer.TrainingStatus|latest'
package: '@azure/ai-form-recognizer'
summary: Defines values for TrainStatus.
fullName: TrainingStatus
remarks: ''
isPreview: false
isDeprecated: false
syntax: type TrainingStatus = "succeeded" | "partiallySucceeded" | "failed"
