### YamlMime:TSTypeAlias
name: FileQueryArrowConfiguration
uid: '@azure/storage-file-datalake.FileQueryArrowConfiguration|latest'
package: '@azure/storage-file-datalake'
summary: >-
  Options to query file with Apache Arrow format. Only valid for
  <xref:@azure/storage-file-datalake.FileQueryOptions.outputTextConfiguration|latest>.
fullName: FileQueryArrowConfiguration
remarks: ''
isPreview: false
isDeprecated: false
syntax: type FileQueryArrowConfiguration = BlobQueryArrowConfiguration
